# Generated by Django 5.2.1 on 2025-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HudebniNastroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('vyrobce', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('strunne', 'Strunné'), ('dechove', 'Dechové'), ('klavesove', 'Klávesové'), ('bici', 'Bicí'), ('jine', 'Jiné')], max_length=20)),
                ('popis', models.TextField(blank=True)),
                ('dostupnost', models.BooleanField(default=True)),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='nastroje/')),
                ('rok_vyroby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hudební nástroj',
                'verbose_name_plural': 'Hudební nástroje',
            },
        ),
    ]
