# Generated by Django 5.2.1 on 2025-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nastroje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hudebninastroj',
            old_name='rok_vyroby',
            new_name='cena',
        ),
        migrations.AddField(
            model_name='hudebninastroj',
            name='barva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hudebninastroj',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hudebninastroj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='nastroje/'),
        ),
    ]
