# Generated by Django 5.2.1 on 2025-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nastroje', '0002_rename_rok_vyroby_hudebninastroj_cena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hudebninastroj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='media/nastroje'),
        ),
    ]
