# Generated by Django 5.2.1 on 2025-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nastroje', '0003_alter_hudebninastroj_obrazek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hudebninastroj',
            name='dostupnost',
        ),
        migrations.AlterField(
            model_name='hudebninastroj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
