# Generated by Django 5.2.2 on 2025-06-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nastroje', '0005_auto_create_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hudebninastroj',
            name='vyrobce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nastroje', to='nastroje.vyrobce', verbose_name='Výrobce'),
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor recenze')),
                ('hodnoceni', models.IntegerField(choices=[(1, '1 hvězda'), (2, '2 hvězdy'), (3, '3 hvězdy'), (4, '4 hvězdy'), (5, '5 hvězd')], verbose_name='Hodnocení')),
                ('text', models.TextField(verbose_name='Text recenze')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum přidání')),
                ('nastroj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to='nastroje.hudebninastroj', verbose_name='Hudební nástroj')),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['-datum'],
            },
        ),
    ]
